Ejercicio 1.1

Vamos a comparar la mioglobina humana (homo sapiens) con la mioglobina bovina (bos taurus) y la mioglobina porcina (sus scrofa).

Humana: MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG

Bovina: MGLSDGEWQLVLNAWGKVEADVAGHGQEVLIRLFTGHPETLEKFDKFKHLKTEAEMKASEDLKKHGNTVLTALGGILKKKGHHEAEVKHLAESHANKHKIPVKYLEFISDAIIHVLHAKHPSDFGADAQAAMSKALELFRNDMAAQYKVLGFHG

Porcina: MGLSDGEWQLVLNVWGKVEADVAGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGNTVLTALGGILKKKGHHEAELTPLAQSHATKHKIPVKYLEFISEAIIQVLQSKHPGDFGADAQGAMSKALELFRNDMAAKYKELGFQG

I) En la sección "alignments" se puede ver que ambas comparaciones toman los 154 aminoácidos, lo que significa que es un alineamiento global.

II) No hay gaps en los dot-plot, solo matches y mismatches. Si hubieran gaps, se verían como huecos entre lineas continuas.

III) Comparando con la bovina, el alineamiento óptimo tiene un score de 267, que es muy alto y un E-value de 2e-98, que es extremadamente bajo. En identities se ve que matchean el 84% de aminoácidos, y el 89% son aminoácidos similares. Hay 0 gaps.
Comparando con la porcina, se ven resultados similares al caso anterior, un score de 294, un E-value aún mas bajo (5e-109), 94% de matches, 96% de aminoácidos similares y 0 gaps.

Si cambio a BLOSUM80, los alineamientos se mantienen igual, pero en ambos casos el score aumenta, el E-value disminuye, y las identidades y positives se mantienen casi igual (varían 1%).

Si cambio los valores de gap existence y extension a 11:2, sucede lo mismo que antes, pero el E-value disminuye todavía más.

Si cambio los valores de gap existence y extension a 9:1, pasa lo opuesto. Los E-values aumentan bastante para ambos casos, y el score disminuye.

Cuando cambiamos a BLOSUM80 los resultados observados concuerdan con el hecho de que son proteínas con mucha similitud, y BLOSUM80 sirve para esas comparaciones, aumentando los score por match y penalizando los gaps (que en estos casos no existieron). Luego, cuando usamos 11:2, estamos haciendo que la evaluación sea mas estricta, y como siguen sin haber gaps, el score general aumenta. Finalmente cuando usamos 9:1, estamos siendo menos estrictos con la evaluación, por lo que disminuye el score.

Ejercicio 1.2

I) Podría utilizar otras bases con datos no redundantes y además curados, como Swiss-Prot y RefSeq. Si hacemos la búsqueda usando la base refseq_protein y baja a 5 resultados, donde 2 son mioglobina de nuevo y 2 son citoglobina. En cambio al usar la base refseq_select directamente no hay repeticiones (isoformes).

II) Citoglobina: Se cree que promueve la difusión de oxígeno en los tejidos. El alineamiento con la mioglobina da un score de 73.6 en BLAST, y un E-value de 5e-17, lo que nos indica que es muy probable que haya una relación biológica entre ambas proteínas.

Hemoglobina subunidad z: Proteína esencial para el transporte de oxígeno en las primeras semanas de gestación. El alineamiento con la mioglobina tiene un score de 71.6 en BLAST, y con un E-value de 1e-16 se puede afirmar que comparten relación biológica.

III) Según BLAST, la proteína mas parecida es la citoglobina, ya que es la de mayor score, menor E-value y mayores valores de identidad. No es sorprendente ya que es una globina también.

IV) No creemos que estas sean todas las globinas, ya que BLAST puede haber omitido algunas por no ser del todo similares. Pueden haber globinas que hayan evolucionado para tener una función distinta a la mioglobina.

V) Como queremos encontrar mas proteínas con un origen común, vamos a reducir el word size a 3, usar la matriz BLOSUM45 en vez de la BLOSUM60 y poner una penalización 13:2. Al ejecutar BLAST, aparecen mas subunidades de hemoglobina (alfa, beta, theta, etc.).

VI) Al utilizar PSI-BLAST, luego de una iteración aparecieron 3 proteínas nuevas, fueron 2 subunidades mas de la hemoglobina y la neuroglobina. Al realizar otra iteración, no obtuvimos nuevas proteínas.

In [65]:
#Ejercicio 2.1 drrA

import pandas as pd

def lee_tsv(nombre_file: str):
    df = pd.read_csv(nombre_file, sep="\t", header=None)
    df.columns = ["query", "identidad", "longitud", "e-value", "bitscore", "query seq", "subject seq"]
    return df

lee_tsv("qdrrA.tsv")

,query,identidad,longitud,e-value,bitscore,query seq,subject seq
0,VFG018236(gb|WP_010948166),100.000,647,0.000000e+00,1333.0,MSIMGRIKMSVNEEQFGSLYSDERDKPLLSPTAQKKFEEYQNKLAN...,MSIMGRIKMSVNEEQFGSLYSDERDKPLLSPTAQKKFEEYQNKLAN...
1,VFG018237(gb|WP_041173820),99.382,647,0.000000e+00,1328.0,MSIMGRIKMSVNEEQFGSLYSDERDKPLLSPTAQKKFEEYQNKLAN...,MSIMGRIKMSVNEEQFGSLYSDERDKPLLSPTAQKKFEEYQNKLAN...
2,VFG041262(gb|WP_010946835),27.907,129,4.650000e-09,58.5,ETLESVLSSKGENLSEYLSYKYATKDEGREHRYTASTE---NFKNV...,EYFKEILTNCDIAVKEYLNGKIGS----RFHLFTAKVDEKTGDQSF...
3,VFG045589(gb|WP_010948303),38.272,81,1.730000e-06,50.8,KEKYQQMRGDALKTEILADFKDKLAEATDEQSLKQIVAELKSKDEY...,QEIYEGLKGDGLKKVILKELRDSLAEIRTMEQLEEKKLEFLASPEM...

In [66]:
#Ejercicio 2.1 map2k7
lee_tsv("qmap2k7.tsv")

,query,identidad,longitud,e-value,bitscore,query seq,subject seq
0,VFG019987(gb|WP_004351957),30.159,252,1.630000e-18,88.2,EMGSGTCGQVWKMRFRKTGHVIAVKQMRRS--GNKEENKRILMDLD...,ELGEGAMATVYLATQRSLQRKVALKVMAAALAADPSFAERFLREGR...
1,VFG015390(gb|WP_011064246),30.830,253,2.060000e-18,87.8,GEMGSGTCGQVWKMRFRKTGHVIAVKQMRRSGNKEEN--KRILMDL...,GEIGEGAMASVYLATQRSLERKVALKVMAAALAADPSFCERFLREG...
2,VFG015386(gb|WP_011979125),30.159,252,3.010000e-18,87.4,EMGSGTCGQVWKMRFRKTGHVIAVKQMRRS--GNKEENKRILMDLD...,ELGEGAMATVYLATQRSLQRKVALKVMAAALAADPSFAERFLREGR...
3,VFG002060(gb|NP_248764),29.762,252,6.580000e-18,86.3,EMGSGTCGQVWKMRFRKTGHVIAVKQMRRS--GNKEENKRILMDLD...,ELGEGAMATVYLATQRSLQRKVALKVMAAALAADPSFAERFLREGR...
4,VFG015387(gb|WP_003136961),29.762,252,7.330000e-18,86.3,EMGSGTCGQVWKMRFRKTGHVIAVKQMRRS--GNKEENKRILMDLD...,ELGEGAMATVYLATQRSLQRKVALKVMAAALAADPSFAERFLREGR...
5,VFG019988(gb|WP_015886548),30.153,262,1.730000e-17,85.1,GEMGSGTCGQVWKMRFRKTGHVIAVKQMRRSGNKEEN--KRILMDL...,GEIGEGAMASVYLATQRSLERKVALKVMAAALAADPSFCERFLREG...
6,VFG008410(gb|YP_005360790),28.992,238,1.660000e-15,77.8,GEMGSGTCGQVWKMRFRKTGHVIAVKQM--RRSGNKEENKRILMDL...,AKIASGGTSTVYRGLDVRLDRPVALKVMDSRYAGDEQFLTRFRLEA...
7,VFG015391(gb|WP_012018656),27.969,261,1.980000e-15,78.6,EINDLENLGEMGSGTCGQVWKMRFRKTGHVIAVKQMRRSGNKEEN-...,EIPGYEIERELGDGAMAVVYLATQRSLERKVALKVMAAALAADPSF...
8,VFG041029(gb|NP_250362),28.507,221,3.870000e-12,67.0,MGSGTCGQVWKMR------FRKTGHVIAVKQMRRSGNKEENKRILM...,LGAGGMGTVYRARDLLHEQFGDPAPLVALKLLNESVAESPDASALL...
9,VFG015592(gb|WP_009873285),31.690,142,4.520000e-12,67.4,KHGVIHRDVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCA...,RHGVLHLDIKPENIVLSQSGEIKLIDYGLSA------WQFNHWGSP...
10,VFG002148(gb|NP_220192),30.128,156,4.850000e-12,67.4,MTVAIVKALYYLKEKHGVIHRDVKPSNILLDERGQIKLCDFGISGR...,IVLQVAQAITTL-HRHGVLHLDIKPENIVLSQSGEIKLIDYGLSA-...
11,VFG016985(gb|WP_011096785),27.236,246,7.080000e-12,67.0,VKQMRRSGNKEENKRILMDLDVVLKSHDCPYIVQCFGTFITNTDVF...,VADTRRVHNFLKEARIIEQV-----SH--PNIVKLYQYGQCRERLY...
12,VFG016986(gb|WP_011006012),28.070,171,9.640000e-12,66.6,PYIVQCFGTFITNTDVFIAME-LMGTCAEKLKKRMQGPIPERILGK...,PNIVKLYQYGQCREGLYIAMEYIQGVSLRHYILSQLIPLSRAI--D...
13,VFG016980(gb|WP_010229205),29.167,144,6.030000e-10,60.8,KHGVIHRDVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCA...,KHHVLHLDIKPENIMISRLGEVKLIDYGLSA------WQFNHWGSP...
14,VFG016987(gb|WP_011458511),26.744,172,9.150000e-09,57.4,PYIVQCFGTFITNTDVFIAME-LMGTCAEKLKKRMQGPIPERILGK...,PNIVKLYQYGQCREGLYMAMEHIQGVSLRKYILSQLIPLSRAV--D...
15,VFG022544(gb|WP_012392663),29.947,187,2.890000e-08,55.8,IAVKQMRRSGNKEENKRILMDLDVVLKSHDCPYIVQCFGTFITNTD...,VVLKGLVHSGDAEA-QAIAMAERQFLAEVVHPSIVQIF-NFVEHTD...
16,VFG008398(gb|WP_015354395),29.947,187,2.950000e-08,55.8,IAVKQMRRSGNKEENKRILMDLDVVLKSHDCPYIVQCFGTFITNTD...,VVLKGLVHSGDAEA-QAIAMAERQFLAEVVHPSIVQIF-NFVEHTD...
17,VFG041279(gb|WP_010947212),39.785,93,7.420000e-08,54.3,KMTVAIVKALY-YLKEKHGVIHRDVKPSNILLDERGQ---IKLCDF...,EITFAILKAIKEQVTDKH-LIHRDIKPGNIIIDFSKSPPIAKVIDF...
18,VFG008236(gb|WP_071497591),29.947,187,1.140000e-07,53.9,IAVKQMRRSGNKEENKRILMDLDVVLKSHDCPYIVQCFGTFITNTD...,VVLKGLVHSGDAEA-QAIAMAERQFLAEVVHPSIVQIF-NFVEHTD...
19,VFG008396(gb|WP_015289020),31.410,156,1.190000e-07,53.9,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
20,VFG008228(gb|NP_214924),31.410,156,1.200000e-07,53.9,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
21,VFG008397(gb|WP_015292139),31.410,156,1.220000e-07,53.9,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
22,VFG022546(gb|WP_003910120),31.410,156,1.280000e-07,53.9,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
23,VFG008395(gb|WP_014000216),31.410,156,1.310000e-07,53.9,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
24,VFG016981(gb|WP_010883341),26.415,212,2.590000e-07,52.8,VFIAMELM-GTCAEKLKKRMQGPIPERILGKMTVAIVKALYYLKEK...,LYIAMEYIEGISLREYILAQFISLPQAI--DIIFDIAQALEHLHSR...
25,VFG008407(gb|YP_007956600),31.410,156,2.710000e-07,52.8,PYIVQCFGTFITNTD------VFIAMELMGTCAEKLKKRMQGPIPE...,PSIVQIF-NFVEHTDRHGDPVGYIVMEYVGGQSLKRSKGQKLPVAE...
26,VFG016984(gb|WP_011126209),26.415,212,2.850000e-07,52.4,VFIAMELM-GTCAEKLKKRMQGPIPERILGKMTVAIVKALYYLKEK...,LYIAMEYIEGISLREYILAQFISLPQAI--DIIFDIAQALEHLHSR...

In [67]:
#Ejercicio 2.1 ndk
lee_tsv("qndk.tsv")

,query,identidad,longitud,e-value,bitscore,query seq,subject seq
0,VFG031464(gb|WP_011893513),48.855,131,2.730000e-38,126,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRRLIGEIISRIEAKGLAIVALELKNVGDDTARA...
1,VFG031462(gb|WP_011724307),45.802,131,1.010000e-37,125,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIIGRIERKGLTLVALELRHVSQDLAAQ...
2,VFG031457(gb|NP_216961),46.565,131,2.790000e-37,124,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGIERQLIGEIISRIERKGLTIAALQLRTVSAELASQ...
3,VFG031461(gb|WP_003875860),45.038,131,5.080000e-37,123,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIIGRIERKGLTLVALELRHVSQDLAAQ...
4,VFG031486(gb|WP_009955946),43.511,131,1.920000e-36,122,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIIGRIERKGLTLAALKLRHVSQDLAAQ...
5,VFG031491(gb|WP_015293694),45.038,131,3.860000e-36,121,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGIERQLIGEIISRIERKGLTIAALQLRTVSAELASQ...
6,VFG031465(gb|WP_011729972),45.038,131,4.650000e-36,120,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVKRQLVGEILSRIERKGLTLAALELKNVSDDLARQ...
7,VFG031466(gb|WP_041309748),45.802,131,4.800000e-36,120,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRRLVGEILGRIERKGLTLAALELKTVDDELARR...
8,VFG031478(gb|WP_012395377),45.038,131,1.660000e-35,119,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIISRIERKGLAIAALELRNVTEELASQ...
9,VFG031471(gb|WP_011781105),45.802,131,1.960000e-35,119,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRRLIGEIISRIEAKGLTVAALELKNVDDALARA...
10,VFG031482(gb|WP_014382181),42.748,131,3.060000e-35,119,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIIGRIERKGLTLAALILRHVSQDLAAQ...
11,VFG031510(gb|WP_041312469),45.038,131,3.170000e-35,119,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRRLIGEILGRIEGKGLSVAALELKNVSDDLARR...
12,VFG031508(gb|WP_008255201),42.748,131,3.380000e-35,118,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRQLVGEIIGRIERKGLTLAALELRHVGQDLAAQ...
13,VFG031470(gb|WP_011741443),45.038,131,6.500000e-35,118,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVQRLLVGEIISRIERKGLAIAALELRNVTEELASQ...
14,VFG031473(gb|YP_001702345),45.038,131,8.080000e-35,117,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVRRGLVGEVLNRIERKGLTLAALELKNVDDATARA...
15,VFG031459(gb|WP_010908355),45.802,131,2.380000e-34,116,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDAVERQLIGEIISRIERKGLTIAALELRQVGEELASQ...
16,VFG031479(gb|WP_041319710),43.511,131,5.440000e-33,113,ERTFSIIKPNAVAKNVIGNIFARFEAAGFKIVGTKMLHLTVEQARG...,ERTLVLIKPDGVNRRLVGEIISRIEKKGLTLAALELRPVQQAVARQ...

Acá debería ir la conclusión pero no entiendo nada.
Creo que map2k7 no pertenece a las cosas virulentas por la baja identidad hallada en todos los hits, en cambio drrA es clave y ndk también

In [68]:
#Ejercicio 2.2

import Bio.SearchIO as bpio

filas = []
resultados = list(bpio.parse("n315_vfdb.xml","blast-xml"))
for result_query in resultados:
    query_len = result_query.seq_len
    for hit in result_query:
        hit_len = hit.seq_len
        for hsp in hit.hsps:
            qcov = hsp.aln_span / query_len * 100
            hcov = hsp.aln_span / hit_len * 100
            identidad = hsp.ident_num / hsp.aln_span * 100
            descripcion = hit.description
            especie = descripcion.split("OS=")[-1].split(" ")[0] if "OS=" in descripcion else "NA"
            filas.append({"query": result_query.id,
                          "hit": hit.id,
                          "cov query": qcov,
                          "cov hit": hcov,
                          "identidad": identidad,
                          "especie": especie})
df = pd.DataFrame(filas)
df.head()

,query,hit,cov query,cov hit,identidad,especie
0,VFG037203(gb|WP_000079188),tr|Q2FWG8|Q2FWG8_STAA8,72.828096,79.757085,20.558376,Staphylococcus
1,VFG037203(gb|WP_000079188),tr|Q2FYW4|Q2FYW4_STAA8,73.937153,81.135903,21.250000,Staphylococcus
2,VFG037201(gb|WP_000079186),tr|Q2FWG8|Q2FWG8_STAA8,72.828096,79.757085,20.558376,Staphylococcus
3,VFG037201(gb|WP_000079186),tr|Q2FYW4|Q2FYW4_STAA8,73.937153,81.135903,21.250000,Staphylococcus
4,VFG037209(gb|WP_000079185),tr|Q2FWG8|Q2FWG8_STAA8,72.828096,79.757085,20.558376,Staphylococcus

In [69]:
#Ejercicio 2.3.a  no se si cumplo con la consigna, puedo afirmar que son las etoxinas presentes si no indico cosas sobre evalue, identidad y cobertura total???

df = pd.read_csv("n315_enterotoxinas.tsv", sep="\t", header=None)
df.columns = ["query", "hit", "identidad", "cov query", "longitud", "e-value", "bitscore"]
etoxinas = df["query"].unique()
lista_toxinas = []
for toxina in etoxinas:
    lista_toxinas.append(toxina)
print("Lista de enterotoxinas presentes en N315:", lista_toxinas)

Lista de enterotoxinas presentes en N315: ['Gr2/selz', 'Gr1/sel26', 'Gr3/sel27', 'Gr4/sel28', 'Gr5/sel29p', 'Gr6/sel30', 'Gr7/ses-2p', 'Gr8/sel31', 'Gr9/sel32', 'Gr10/sel33', 'Gr11/seh-2p', 'Gr12/ses-3p', 'tsst-1', 'selx', 'sea', 'seb', 'sec1', 'sec2', 'sec3', 'sed', 'see', 'seg', 'seh', 'sei', 'selj', 'sek', 'sel', 'sem', 'sen', 'seo', 'sep', 'seq', 'ser', 'ses', 'set', 'selu', 'selv', 'selw', 'sely']

In [70]:
#Ejercicio 2.3.b voy a usar la identidad y cobertura para afirmar que estas si estan en el proteoma
df = df[(df["cov query"] > 70) & (df["identidad"] > 80)]
etoxinas_filtradas = df["query"].unique()
lista_filtrada = []
for tox in etoxinas_filtradas:
    lista_filtrada.append(tox)
print("Lista de enterotoxinas filtradas en n315:", lista_filtrada)

Lista de enterotoxinas filtradas en n315: ['Gr1/sel26', 'selx']